### ISSUE TITLE
Any chance of integration/dependency on SystemHeat mod by Nertea?

### ISSUE THREAD

**Issue by JordanRL** [Kerbalism/Kerbalism4#29]
The thermal management aspect of Kerbalism is by far the least interesting and most frustrating aspect just because the heating system itself is so bad. I'm curious if for 4.0 the SystemHeat mod is being considered at all?

**Comment by gotmachine** [comment]
Short answer : no

Slightly longer answer : there are technical reasons that make integration with SystemHeat (as well as Near Future Electric stuff) impossible. I do however have plans for a thermal management system in Kerbalism 4. The details are still undecided, but it will likely be quite similar to System Heat.
